export const COUNTRIES = [
  { code: "AF", name: "Afghanistan", emoji: "🇦🇫", continent: "Asia" },
  { code: "AL", name: "Albania", emoji: "🇦🇱", continent: "Europe" },
  { code: "DZ", name: "Algeria", emoji: "🇩🇿", continent: "Africa" },
  { code: "AD", name: "Andorra", emoji: "🇦🇩", continent: "Europe" },
  { code: "AO", name: "Angola", emoji: "🇦🇴", continent: "Africa" },
  { code: "AG", name: "Antigua and Barbuda", emoji: "🇦🇬", continent: "Americas" },
  { code: "AR", name: "Argentina", emoji: "🇦🇷", continent: "Americas" },
  { code: "AM", name: "Armenia", emoji: "🇦🇲", continent: "Asia" },
  { code: "AU", name: "Australia", emoji: "🇦🇺", continent: "Oceania" },
  { code: "AT", name: "Austria", emoji: "🇦🇹", continent: "Europe" },
  { code: "AZ", name: "Azerbaijan", emoji: "🇦🇿", continent: "Asia" },
  { code: "BS", name: "Bahamas", emoji: "🇧🇸", continent: "Americas" },
  { code: "BH", name: "Bahrain", emoji: "🇧🇭", continent: "Asia" },
  { code: "BD", name: "Bangladesh", emoji: "🇧🇩", continent: "Asia" },
  { code: "BB", name: "Barbados", emoji: "🇧🇧", continent: "Americas" },
  { code: "BY", name: "Belarus", emoji: "🇧🇾", continent: "Europe" },
  { code: "BE", name: "Belgium", emoji: "🇧🇪", continent: "Europe" },
  { code: "BZ", name: "Belize", emoji: "🇧🇿", continent: "Americas" },
  { code: "BJ", name: "Benin", emoji: "🇧🇯", continent: "Africa" },
  { code: "BT", name: "Bhutan", emoji: "🇧🇹", continent: "Asia" },
  { code: "BO", name: "Bolivia", emoji: "🇧🇴", continent: "Americas" },
  { code: "BA", name: "Bosnia and Herzegovina", emoji: "🇧🇦", continent: "Europe" },
  { code: "BW", name: "Botswana", emoji: "🇧🇼", continent: "Africa" },
  { code: "BR", name: "Brazil", emoji: "🇧🇷", continent: "Americas" },
  { code: "BN", name: "Brunei", emoji: "🇧🇳", continent: "Asia" },
  { code: "BG", name: "Bulgaria", emoji: "🇧🇬", continent: "Europe" },
  { code: "KH", name: "Cambodia", emoji: "🇰🇭", continent: "Asia" },
  { code: "CM", name: "Cameroon", emoji: "🇨🇲", continent: "Africa" },
  { code: "CA", name: "Canada", emoji: "🇨🇦", continent: "Americas" },
  { code: "CL", name: "Chile", emoji: "🇨🇱", continent: "Americas" },
  { code: "CN", name: "China", emoji: "🇨🇳", continent: "Asia" },
  { code: "CO", name: "Colombia", emoji: "🇨🇴", continent: "Americas" },
  { code: "CR", name: "Costa Rica", emoji: "🇨🇷", continent: "Americas" },
  { code: "HR", name: "Croatia", emoji: "🇭🇷", continent: "Europe" },
  { code: "CU", name: "Cuba", emoji: "🇨🇺", continent: "Americas" },
  { code: "CY", name: "Cyprus", emoji: "🇨🇾", continent: "Europe" },
  { code: "CZ", name: "Czech Republic", emoji: "🇨🇿", continent: "Europe" },
  { code: "DK", name: "Denmark", emoji: "🇩🇰", continent: "Europe" },
  { code: "DO", name: "Dominican Republic", emoji: "🇩🇴", continent: "Americas" },
  { code: "EC", name: "Ecuador", emoji: "🇪🇨", continent: "Americas" },
  { code: "EG", name: "Egypt", emoji: "🇪🇬", continent: "Africa" },
  { code: "SV", name: "El Salvador", emoji: "🇸🇻", continent: "Americas" },
  { code: "EE", name: "Estonia", emoji: "🇪🇪", continent: "Europe" },
  { code: "ET", name: "Ethiopia", emoji: "🇪🇹", continent: "Africa" },
  { code: "FI", name: "Finland", emoji: "🇫🇮", continent: "Europe" },
  { code: "FR", name: "France", emoji: "🇫🇷", continent: "Europe" },
  { code: "DE", name: "Germany", emoji: "🇩🇪", continent: "Europe" },
  { code: "GH", name: "Ghana", emoji: "🇬🇭", continent: "Africa" },
  { code: "GR", name: "Greece", emoji: "🇬🇷", continent: "Europe" },
  { code: "GT", name: "Guatemala", emoji: "🇬🇹", continent: "Americas" },
  { code: "HN", name: "Honduras", emoji: "🇭🇳", continent: "Americas" },
  { code: "HU", name: "Hungary", emoji: "🇭🇺", continent: "Europe" },
  { code: "IS", name: "Iceland", emoji: "🇮🇸", continent: "Europe" },
  { code: "IN", name: "India", emoji: "🇮🇳", continent: "Asia" },
  { code: "ID", name: "Indonesia", emoji: "🇮🇩", continent: "Asia" },
  { code: "IR", name: "Iran", emoji: "🇮🇷", continent: "Asia" },
  { code: "IQ", name: "Iraq", emoji: "🇮🇶", continent: "Asia" },
  { code: "IE", name: "Ireland", emoji: "🇮🇪", continent: "Europe" },
  { code: "IL", name: "Israel", emoji: "🇮🇱", continent: "Asia" },
  { code: "IT", name: "Italy", emoji: "🇮🇹", continent: "Europe" },
  { code: "JM", name: "Jamaica", emoji: "🇯🇲", continent: "Americas" },
  { code: "JP", name: "Japan", emoji: "🇯🇵", continent: "Asia" },
  { code: "JO", name: "Jordan", emoji: "🇯🇴", continent: "Asia" },
  { code: "KZ", name: "Kazakhstan", emoji: "🇰🇿", continent: "Asia" },
  { code: "KE", name: "Kenya", emoji: "🇰🇪", continent: "Africa" },
  { code: "KR", name: "South Korea", emoji: "🇰🇷", continent: "Asia" },
  { code: "KW", name: "Kuwait", emoji: "🇰🇼", continent: "Asia" },
  { code: "LV", name: "Latvia", emoji: "🇱🇻", continent: "Europe" },
  { code: "LB", name: "Lebanon", emoji: "🇱🇧", continent: "Asia" },
  { code: "LT", name: "Lithuania", emoji: "🇱🇹", continent: "Europe" },
  { code: "LU", name: "Luxembourg", emoji: "🇱🇺", continent: "Europe" },
  { code: "MY", name: "Malaysia", emoji: "🇲🇾", continent: "Asia" },
  { code: "MV", name: "Maldives", emoji: "🇲🇻", continent: "Asia" },
  { code: "MT", name: "Malta", emoji: "🇲🇹", continent: "Europe" },
  { code: "MX", name: "Mexico", emoji: "🇲🇽", continent: "Americas" },
  { code: "MA", name: "Morocco", emoji: "🇲🇦", continent: "Africa" },
  { code: "MZ", name: "Mozambique", emoji: "🇲🇿", continent: "Africa" },
  { code: "MM", name: "Myanmar", emoji: "🇲🇲", continent: "Asia" },
  { code: "NP", name: "Nepal", emoji: "🇳🇵", continent: "Asia" },
  { code: "NL", name: "Netherlands", emoji: "🇳🇱", continent: "Europe" },
  { code: "NZ", name: "New Zealand", emoji: "🇳🇿", continent: "Oceania" },
  { code: "NI", name: "Nicaragua", emoji: "🇳🇮", continent: "Americas" },
  { code: "NG", name: "Nigeria", emoji: "🇳🇬", continent: "Africa" },
  { code: "NO", name: "Norway", emoji: "🇳🇴", continent: "Europe" },
  { code: "OM", name: "Oman", emoji: "🇴🇲", continent: "Asia" },
  { code: "PK", name: "Pakistan", emoji: "🇵🇰", continent: "Asia" },
  { code: "PA", name: "Panama", emoji: "🇵🇦", continent: "Americas" },
  { code: "PY", name: "Paraguay", emoji: "🇵🇾", continent: "Americas" },
  { code: "PE", name: "Peru", emoji: "🇵🇪", continent: "Americas" },
  { code: "PH", name: "Philippines", emoji: "🇵🇭", continent: "Asia" },
  { code: "PL", name: "Poland", emoji: "🇵🇱", continent: "Europe" },
  { code: "PT", name: "Portugal", emoji: "🇵🇹", continent: "Europe" },
  { code: "QA", name: "Qatar", emoji: "🇶🇦", continent: "Asia" },
  { code: "RO", name: "Romania", emoji: "🇷🇴", continent: "Europe" },
  { code: "RU", name: "Russia", emoji: "🇷🇺", continent: "Europe" },
  { code: "SA", name: "Saudi Arabia", emoji: "🇸🇦", continent: "Asia" },
  { code: "SN", name: "Senegal", emoji: "🇸🇳", continent: "Africa" },
  { code: "RS", name: "Serbia", emoji: "🇷🇸", continent: "Europe" },
  { code: "SG", name: "Singapore", emoji: "🇸🇬", continent: "Asia" },
  { code: "SK", name: "Slovakia", emoji: "🇸🇰", continent: "Europe" },
  { code: "SI", name: "Slovenia", emoji: "🇸🇮", continent: "Europe" },
  { code: "ZA", name: "South Africa", emoji: "🇿🇦", continent: "Africa" },
  { code: "ES", name: "Spain", emoji: "🇪🇸", continent: "Europe" },
  { code: "LK", name: "Sri Lanka", emoji: "🇱🇰", continent: "Asia" },
  { code: "SE", name: "Sweden", emoji: "🇸🇪", continent: "Europe" },
  { code: "CH", name: "Switzerland", emoji: "🇨🇭", continent: "Europe" },
  { code: "TW", name: "Taiwan", emoji: "🇹🇼", continent: "Asia" },
  { code: "TZ", name: "Tanzania", emoji: "🇹🇿", continent: "Africa" },
  { code: "TH", name: "Thailand", emoji: "🇹🇭", continent: "Asia" },
  { code: "TN", name: "Tunisia", emoji: "🇹🇳", continent: "Africa" },
  { code: "TR", name: "Turkey", emoji: "🇹🇷", continent: "Europe" },
  { code: "UA", name: "Ukraine", emoji: "🇺🇦", continent: "Europe" },
  { code: "AE", name: "United Arab Emirates", emoji: "🇦🇪", continent: "Asia" },
  { code: "GB", name: "United Kingdom", emoji: "🇬🇧", continent: "Europe" },
  { code: "US", name: "United States", emoji: "🇺🇸", continent: "Americas" },
  { code: "UY", name: "Uruguay", emoji: "🇺🇾", continent: "Americas" },
  { code: "UZ", name: "Uzbekistan", emoji: "🇺🇿", continent: "Asia" },
  { code: "VE", name: "Venezuela", emoji: "🇻🇪", continent: "Americas" },
  { code: "VN", name: "Vietnam", emoji: "🇻🇳", continent: "Asia" }
];

export const getCountryByCode = (code) => COUNTRIES.find(c => c.code === code);
export const getCountryName = (code) => getCountryByCode(code)?.name || code;
export const getCountryEmoji = (code) => getCountryByCode(code)?.emoji || "🌍";
export const TOTAL_COUNTRIES = 195;