// Stamp design configurations + PNG filename mapping
export const STAMP_DESIGNS = {
  JP: { color: "#D4374A", icon: "🗼", label: "JAPAN", subtitle: "Land of the Rising Sun", shape: "circle" },
  FR: { color: "#1D3557", icon: "🗼", label: "FRANCE", subtitle: "Liberté, Égalité, Fraternité", shape: "rectangle" },
  IT: { color: "#2E8B57", icon: "🏛️", label: "ITALIA", subtitle: "La Dolce Vita", shape: "circle" },
  ES: { color: "#C62828", icon: "💃", label: "ESPAÑA", subtitle: "Pasión y Cultura", shape: "rectangle" },
  US: { color: "#1A237E", icon: "🗽", label: "USA", subtitle: "Land of the Free", shape: "circle" },
  GB: { color: "#8B0000", icon: "👑", label: "UNITED KINGDOM", subtitle: "God Save the King", shape: "rectangle" },
  DE: { color: "#333333", icon: "🏰", label: "DEUTSCHLAND", subtitle: "Made in Germany", shape: "circle" },
  BR: { color: "#009739", icon: "⚽", label: "BRASIL", subtitle: "Ordem e Progresso", shape: "circle" },
  AU: { color: "#D4A42E", icon: "🦘", label: "AUSTRALIA", subtitle: "Down Under", shape: "rectangle" },
  TH: { color: "#6B21A8", icon: "🛕", label: "THAILAND", subtitle: "Land of Smiles", shape: "circle" },
  MX: { color: "#006847", icon: "🌮", label: "MÉXICO", subtitle: "Viva México", shape: "rectangle" },
  IN: { color: "#FF9933", icon: "🕌", label: "INDIA", subtitle: "Incredible India", shape: "circle" },
  EG: { color: "#C49B2F", icon: "🏛️", label: "EGYPT", subtitle: "Gift of the Nile", shape: "rectangle" },
  GR: { color: "#0D5EAF", icon: "🏛️", label: "HELLAS", subtitle: "Birthplace of Democracy", shape: "circle" },
  TR: { color: "#E30A17", icon: "🕌", label: "TÜRKİYE", subtitle: "Where East Meets West", shape: "rectangle" },
  PT: { color: "#004225", icon: "⛵", label: "PORTUGAL", subtitle: "Os Navegadores", shape: "circle" },
  NL: { color: "#FF6600", icon: "🌷", label: "NEDERLAND", subtitle: "Kingdom of the Netherlands", shape: "rectangle" },
  CH: { color: "#FF0000", icon: "⛰️", label: "SCHWEIZ", subtitle: "Precision & Nature", shape: "circle" },
  KR: { color: "#003478", icon: "🎎", label: "KOREA", subtitle: "Morning Calm", shape: "circle" },
  CA: { color: "#D80621", icon: "🍁", label: "CANADA", subtitle: "True North", shape: "rectangle" },
  AR: { color: "#6CACE4", icon: "⚽", label: "ARGENTINA", subtitle: "Tierra de Pasión", shape: "circle" },
  CO: { color: "#FCD116", icon: "☕", label: "COLOMBIA", subtitle: "Realismo Mágico", shape: "rectangle" },
  MA: { color: "#C1272D", icon: "🕌", label: "MAROC", subtitle: "Gateway to Africa", shape: "circle" },
  PE: { color: "#D91023", icon: "🏔️", label: "PERÚ", subtitle: "Land of the Incas", shape: "rectangle" },
  IS: { color: "#003897", icon: "🌋", label: "ÍSLAND", subtitle: "Land of Fire & Ice", shape: "circle" },
  NZ: { color: "#1A1A1A", icon: "🥝", label: "NEW ZEALAND", subtitle: "Aotearoa", shape: "rectangle" },
  SG: { color: "#ED2939", icon: "🦁", label: "SINGAPORE", subtitle: "Lion City", shape: "circle" },
  AE: { color: "#C5A028", icon: "🏙️", label: "UAE", subtitle: "City of Gold", shape: "rectangle" },
  HR: { color: "#003DA5", icon: "⛵", label: "HRVATSKA", subtitle: "Mediterranean Gem", shape: "circle" },
  VN: { color: "#DA251D", icon: "🍜", label: "VIỆT NAM", subtitle: "Ascending Dragon", shape: "circle" },
  SE: { color: "#006AA7", icon: "🦌", label: "SVERIGE", subtitle: "Lagom", shape: "rectangle" },
  NO: { color: "#BA0C2F", icon: "🏔️", label: "NORGE", subtitle: "Land of the Vikings", shape: "circle" },
  CZ: { color: "#11457E", icon: "🏰", label: "ČESKO", subtitle: "Heart of Europe", shape: "rectangle" },
  IE: { color: "#169B62", icon: "☘️", label: "ÉIRE", subtitle: "Emerald Isle", shape: "circle" },
  PL: { color: "#DC143C", icon: "🏰", label: "POLSKA", subtitle: "Heart of Europe", shape: "rectangle" },
  FI: { color: "#003580", icon: "🌲", label: "SUOMI", subtitle: "Land of a Thousand Lakes", shape: "circle" },
};

// Maps ISO alpha-2 code → PNG filename in /public/stamps/
export const STAMP_PNG_MAP = {
  AF: "Afganistan.png",
  AL: "Albania.png",
  DE: "Alemania.png",
  AD: "Andorra.png",
  AO: "Angola.png",
  AG: "Antigua_y_Barbuda.png",
  SA: "Arabia_Saudi.png",
  DZ: "Argelia.png",
  AR: "Argentina.png",
  AM: "Armenia.png",
  AU: "Australia.png",
  AT: "Austria.png",
  AZ: "Azerbaiyan.png",
  BS: "Bahamas.png",
  BD: "Banglades.png",
  BB: "Barbados.png",
  BH: "Barein.png",
  BE: "Belgica.png",
  BZ: "Belice.png",
  BJ: "Benin.png",
  BY: "Bielorrusia.png",
  MM: "Birmania.png",
  BO: "Bolivia.png",
  BA: "Bosnia_y_Herzegovina.png",
  BW: "Botsuana.png",
  BR: "Brasil.png",
  BN: "Brunei.png",
  BG: "Bulgaria.png",
  BF: "Burkina_Faso.png",
  BI: "Burundi.png",
  BT: "Butan.png",
  CV: "Cabo_Verde.png",
  KH: "Camboya.png",
  CM: "Camerun.png",
  CA: "Canada.png",
  QA: "Catar.png",
  TD: "Chad.png",
  CL: "Chile.png",
  CN: "China.png",
  CY: "Chipre.png",
  CO: "Colombia.png",
  KM: "Comoras.png",
  KP: "Corea_del_Norte.png",
  KR: "Corea_del_Sur.png",
  CR: "Costa_Rica.png",
  CI: "Costa_de_Marfil.png",
  HR: "Croacia.png",
  DK: "Dinamarca.png",
  DM: "Dominica.png",
  EC: "Ecuador.png",
  EG: "Egipto.png",
  SV: "El_Salvador.png",
  AE: "Emiratos_Arabes_Unidos.png",
  ER: "Eritrea.png",
  SK: "Eslovaquia.png",
  SI: "Eslovenia.png",
  ES: "Espana.png",
  PS: "Estado_de_Palestina.png",
  US: "Estados_Unidos.png",
  EE: "Estonia.png",
  SZ: "Esuatini.png",
  ET: "Etiopia.png",
  PH: "Filipinas.png",
  FI: "Finlandia.png",
  FJ: "Fiyi.png",
  FR: "Francia.png",
  GA: "Gabon.png",
  GM: "Gambia.png",
  GE: "Georgia.png",
  GH: "Ghana.png",
  GD: "Granada.png",
  GR: "Grecia.png",
  GT: "Guatemala.png",
  GN: "Guinea.png",
  GW: "Guinea_Bisau.png",
  GQ: "Guinea_Ecuatorial.png",
  GY: "Guyana.png",
  HT: "Haiti.png",
  HN: "Honduras.png",
  HU: "Hungria.png",
  IN: "India.png",
  ID: "Indonesia.png",
  IQ: "Irak.png",
  IR: "Iran.png",
  IE: "Irlanda.png",
  IS: "Islandia.png",
  MH: "Islas_Marshall.png",
  SB: "Islas_Salomon.png",
  IL: "Israel.png",
  IT: "Italia.png",
  JM: "Jamaica.png",
  JP: "Japon.png",
  JO: "Jordania.png",
  KZ: "Kazajistan.png",
  KE: "Kenia.png",
  KG: "Kirguistan.png",
  KI: "Kiribati.png",
  KW: "Kuwait.png",
  LA: "Laos.png",
  LS: "Lesoto.png",
  LV: "Letonia.png",
  LR: "Liberia.png",
  LY: "Libia.png",
  LI: "Liechtenstein.png",
  LT: "Lituania.png",
  LB: "Libano.png",
  LU: "Luxemburgo.png",
  MK: "Macedonia_del_Norte.png",
  MG: "Madagascar.png",
  MY: "Malasia.png",
  MW: "Malaui.png",
  MV: "Maldivas.png",
  ML: "Mali.png",
  MT: "Malta.png",
  MA: "Marruecos.png",
  MU: "Mauricio.png",
  MR: "Mauritania.png",
  FM: "Micronesia.png",
  MD: "Moldavia.png",
  MN: "Mongolia.png",
  ME: "Montenegro.png",
  MZ: "Mozambique.png",
  MX: "Mexico.png",
  MC: "Monaco.png",
  NA: "Namibia.png",
  NR: "Nauru.png",
  NP: "Nepal.png",
  NI: "Nicaragua.png",
  NE: "Niger.png",
  NG: "Nigeria.png",
  NO: "Noruega.png",
  NZ: "Nueva_Zelanda.png",
  OM: "Oman.png",
  PK: "Pakistan.png",
  PW: "Palaos.png",
  PA: "Panama.png",
  PG: "Papúa NuevaGuinea.png",
  PY: "Paraguay.png",
  NL: "Paises_Bajos.png",
  PE: "Peru.png",
  PL: "Polonia.png",
  PT: "Portugal.png",
  GB: "Reino_Unido.png",
  CZ: "Republica_Checa.png",
  CF: "Republica_Centroafricana.png",
  CD: "Republica_Democratica_del_Congo.png",
  DO: "Republica_Dominicana.png",
  CG: "Republica_del_Congo.png",
  RW: "Ruanda.png",
  RO: "Rumania.png",
  RU: "Rusia.png",
  WS: "Samoa.png",
  KN: "San_Cristobal_y_Nieves.png",
  SM: "San_Marino.png",
  VC: "San_Vicente_y_las_Granadinas.png",
  LC: "Santa_Lucia.png",
  ST: "Santo_Tome_y_Principe.png",
  SN: "Senegal.png",
  RS: "Serbia.png",
  SC: "Seychelles.png",
  SL: "Sierra_Leona.png",
  SG: "Singapur.png",
  SY: "Siria.png",
  SO: "Somalia.png",
  LK: "Sri_Lanka.png",
  ZA: "Sudafrica.png",
  SD: "Sudan.png",
  SS: "Sudan_del_Sur.png",
  SE: "Suecia.png",
  CH: "Suiza.png",
  SR: "Surinam.png",
  TH: "Tailandia.png",
  TZ: "Tanzania.png",
  TJ: "Tayikistan.png",
  TL: "Timor_Oriental.png",
  TG: "Togo.png",
  TO: "Tonga.png",
  TT: "Trinidad_y_Tobago.png",
  TM: "Turkmenistan.png",
  TR: "Turquia.png",
  TV: "Tuvalu.png",
  TN: "Tunez.png",
  UA: "Ucrania.png",
  UG: "Uganda.png",
  UY: "Uruguay.png",
  UZ: "Uzbekistan.png",
  VU: "Vanuatu.png",
  VA: "Vaticano.png",
  VE: "Venezuela.png",
  VN: "Vietnam.png",
  YE: "Yemen.png",
  DJ: "Yibuti.png",
  ZM: "Zambia.png",
  ZW: "Zimbabue.png",
  CU: "Cuba.png",
};

export const getStampDesign = (countryCode) => {
  return STAMP_DESIGNS[countryCode] || {
    color: "#6B7280",
    icon: "✈️",
    label: countryCode,
    subtitle: "Visited",
    shape: "circle"
  };
};

export const getStampPngUrl = (countryCode) => {
  const filename = STAMP_PNG_MAP[countryCode];
  if (!filename) return null;
  return `/stamps/${encodeURIComponent(filename)}`;
};
